### ISSUE TITLE
No information exists on how to use this image.

### ISSUE THREAD

**Issue by sam-falvo** [sbates130272/docker-riscv#1]
Would it be possible to include a few pointers on how to use the tools contained inside the image?  I've performed "docker pull", but I'm left bamboozled on what to do next.  Thanks.

**Comment by sbates130272** [comment]
Hi Sam

Good idea. I will add a simple HOWTO. For now try "docker run -it image id" to put you into the container and then use the documentation for the RISC-V tools to do things like run spike on the kernel. See the last lines of the Dockerfile file for a bit more discussion.

Stephen

**Comment by sbates130272** [comment]
This is fixed in 771288d0f96b7e7332394298762b175c618628b5. I added a Getting Started in README.md. Feel free to submit a PR with a more detailed section if you like ;-)!
